version: 0.2

phases:
  install:
    commands:
      - echo "Installing Amazon Corretto 21..."
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
      - yum install -y amazon-corretto-21-x64-linux-jdk.rpm
      - alternatives --install /usr/bin/java java /usr/lib/jvm/java-21-amazon-corretto/bin/java 1
      - alternatives --set java /usr/lib/jvm/java-21-amazon-corretto/bin/java

  pre_build:
    commands:
      - echo "Java version:"
      - java -version
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto

  build:
    commands:
      - echo "Building with Maven..."
      - mvn -DskipTests clean package
      - cp target/*.jar target/application.jar
      - ls -R target

artifacts:
  files:
    - application.jar       
  base-directory: target    
  discard-paths: yes
